name: Deploy a producción

on:
  push:
    branches: [estatico]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy en servidor
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: bash /var/www/soprole/deploy.sh
